name: ecr
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
          
#       - run: |
#           docker pull httpd
#           docker tag httpd system:9.999.9.99999
      
#       - uses: stuart-kennedy/actions/ecr-push@v1.0.19
#         with:
#           repository-url: 533930369772.dkr.ecr.ap-southeast-2.amazonaws.com/ubiquity-ci-image-cache 
#           image: system:9.999.9.99999
#           tags: |
#             latest
#             foo
            
      - uses: stuart-kennedy/actions/ecr-pull@v1.0.19
        with:
          repository-url: 533930369772.dkr.ecr.ap-southeast-2.amazonaws.com/ubiquity-ci-image-cache 
          image: system
          tags: |
            9.999.9.99999
            foo
            bar

      - run: |
          docker image ls
