name: ecr
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: rav2040/set-json-output-action@v1
        id: step_1
        with:
          name: my_value
          cmd: echo '{"foo":"bar"}'
       
       - run: echo ${{ fromJSON(steps.step_1.outputs.my_value).foo }}
