name: merge test

on:
  push:
    branches:
      - release/*

jobs:
  post_build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
#       - name: Generate a token
#         id: generate_token
#         uses: tibdex/github-app-token@b62528385c34dbc9f38e5f4225ac829252d1ea92
#         with:
#           app_id: ${{ secrets.APP_ID }}
#           private_key: ${{ secrets.APP_PRIVATE_KEY }} 

      - name: Generate app token
        id: app_auth
        uses: stuart-kennedy/actions/github-app-auth@v1.0.10
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - run: echo ${{ steps.app_auth.outputs.token }}
          
      - name: Merge to downstream branch TEST
        env:
          GITHUB_TOKEN: ${{ steps.app_auth.outputs.token }}
        run: |
          currentBranch=${{ github.ref_name }}
          readarray -t branches < <(gh api /repos/${{ github.repository }}/branches --paginate --jq '.[].name' | grep -e 'release/' | sort)
          for branch in "${branches[@]}"; do \
            if [[ ${branch/release\//} > ${currentBranch/release\//} ]]; then \
              gh api /repos/${{ github.repository }}/merges \
                -f base=$branch \
                -f head=$currentBranch \
                -f commit_message="Merge $currentBranch into $branch" 
              break
            fi
          done
