name: merge test

on:
  push:
    branches:
      - release/*

jobs:
  post_build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Merge to downstream release branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          currentBranch=${{ github.ref_name }}
          readarray -t branches < <(gh api /repos/${{ github.repository }}/branches --paginate --jq '.[].name' | grep -e 'release/' | sort)
          branch(for b in "${branches[@]}"; do
            if [[ ${branch/release\//} > ${currentBranch/release\//} ]]; then
              echo $b; break
            fi
          done)
          echo "BOOM"
          echo $branch
