name: merge test

on:
  push:
    branches:
      - release/*

jobs:
  post_build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Merge to downstream branch
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          currentBranch=${{ github.ref_name }}
          readarray -t branches < <(gh api /repos/${{ github.repository }}/branches --paginate --jq '.[].name' | grep -e 'release/' | sort)
          for branch in "${branches[@]}"; do \
            if [[ ${branch/release\//} > ${currentBranch/release\//} ]]; then \
              gh api /repos/${{ github.repository }}/merges \
                -f base=$branch \
                -f head=$currentBranch \
                -f commit_message="Merge $currentBranch into $branch" 
              break
            fi
          done

#test
