name: merge test

on:
  push:
    branches:
      - release/*

jobs:
  post_build:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Merge to downstream release branches
        env:
          GITHUB_TOKEN: ${{ secrets.TEST_TOKEN }}
        run: |
          currentBranch=${{ github.ref_name }}
          readarray -t branches < <(gh api /repos/${{ github.repository }}/branches --paginate --jq '.[].name' | grep -e 'release/' | sort)
          for branch in "${branches[@]}"; do \
            if [[ ${branch/release\//} > ${currentBranch/release\//} ]]; then \
              curl -L -X POST \
                -H "Authorization: Bearer ${{ secrets.TEST_TOKEN }}"\
                -H "X-GitHub-Api-Version: 2022-11-28" \
                https://api.github.com/repos/${{ github.repository }}/merges \
                -d '{"base":"'$branch'","head":"'$currentBranch'","commit_message":"Merge '$currentBranch' branch to '$branch'"}'
              break
            fi
          done
