name: merge test

on:
  push:
    branches:
      - release/*

jobs:
  post_build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    permissions:
      pull-requests: write
    steps:
      - name: Generate app token
        id: app_auth
        uses: stuart-kennedy/actions/github-app-auth@v1.0.10
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}

      - name: Determine base and head branches
        id: branches
        run: |
          head=${{ github.ref_name }}
          echo "head=$head" >> $GITHUB_OUTPUT
          readarray -t branches < <(gh api /repos/${{ github.repository }}/branches --paginate --jq '.[].name' | grep -e 'release/' | sort)
          for branch in "${branches[@]}"; do \
            echo "ONE: $branch"
            if [[ ${branch/release\//} > ${head/release\//} ]]; then \
              echo "TWO: $branch"
              echo "base=$branch" >> $GITHUB_OUTPUT; break
            fi
          done

      - name: Merge to downstream branch
        id: auto_merge
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ steps.app_auth.outputs.token }}
        run: |
          base=${{ steps.branches.outputs.base }}
          head=${{ steps.branches.outputs.head }}
          gh api /repos/${{ github.repository }}/merges \
            -f base=$base \
            -f head=$head \
            -f commit_message='Merge \'$head\' into \'$base\''

      - name: Create PR to merge to downstream branch
        if: steps.auto_merge.outcome == 'failure'
        run: |
          base=${{ steps.branches.outputs.base }}
          head=${{ steps.branches.outputs.head }}
          gh api /repos/${{ github.repository }}/pulls \
            -f base=$base \
            -f head=$head \
            -f title='Merge \'$head\' into \'$base\'' \
            -f body='This pull request was automatically created as a result of a failed downstream auto-merge.'
            
      - name: Auto-merge failed
        if: steps.auto_merge.outcome == 'failure'
        run: exit 1
