name: merge test

on:
  push:
    branches:
      - release/*

jobs:
  post_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Merge to downstream release branches
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          currentBranch=${{ github.ref_name }}
          branches=$(gh api /repos/${{ github.repository }}/branches --paginate --jq '.[].name' | grep -e 'release/')
          for branch in $branches; do \
            if [[ ${branch/release\//} > ${currentBranch/release\//} ]]; then \
              gh workflow run merge-upstream.yml --ref release/1.159.0 -f base=$branch -f head=${{ github.sha }}
            fi
          done
