name: merge test

on:
  push:
    branches:
      - release/*

jobs:
  post_build:
    runs-on: ubuntu-latest
    steps:
      - name: Generate app token
        id: app_auth
        uses: stuart-kennedy/actions/github-app-auth@v1.0.10
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
          
      - name: Merge to downstream branch
        id: auto_merge
        continue-on-error: true
        env:
          GITHUB_TOKEN: ${{ steps.app_auth.outputs.token }}
        run: |
          currentBranch=${{ github.ref_name }}
          readarray -t branches < <(gh api /repos/${{ github.repository }}/branches --paginate --jq '.[].name' | grep -e 'release/' | sort)
          for branch in "${branches[@]}"; do \
            if [[ ${branch/release\//} > ${currentBranch/release\//} ]]; then \
              gh api /repos/${{ github.repository }}/merges \
                -f base=$branch \
                -f head=$currentBranch \
                -f commit_message="Merge $currentBranch into $branch" 
              break
            fi
          done
          
      - name: Create PR to merge to downstream branch
        if: steps.auto_merge.outcome == 'failure'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh api /repos/${{ github.repository }}/pulls \
            -f base=$branch \
            -f head=$currentBranch \
            -f title="Merge '$currentBranch' into '$branch'" \
            -f body="This pull request was automatically created as a result of a failed downstream auto-merge."

