name: test
on:
  push:
    branches: ["*"]

jobs:
  build:
    timeout-minutes: 45
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2

      - name: ECHO TEST
        run: |
          echo '{"hello":"world"}'
