name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - run: |
          mkdir -p foo/bar/baz/boom
          ls foo
          ls foo/bar
          ls foo/bar/baz
          
      - uses: rav2040/s3-upload-action@improvements
        with:
          bucket: stuart-s3-cache-test
          prefix: my_prefix
          path: |
            .docker
            foo

#       - run: |
#           rm -rf foo
#           rm -rf .docker
#           ls -al
            
#       - uses: actions/download-artifact@v3
#         with:
#           name: my-artifact

#       - run: |
#           ls foo
#           ls foo/bar
#           ls foo/bar/baz
