name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ vars.AWS_REGION }}
      
      - uses: rav2040/s3-upload-action@v1
        with:
          bucket: stuart-s3-cache-test
          prefix: 1
          path: |
            .docker
            foo

      - uses: rav2040/s3-download-action@main
        with:
          bucket: stuart-s3-cache-test
          prefix: 1
          path: |
            .docker
            foo
