name: test
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: push test
        uses: rav2040/upload-artifact-action@v1
        with:
          path: |
            .docker/foo/**/*
            .docker/bar/**/*
          
      - name: Delete local dir
        shell: bash
        run: rm -rf .docker

      - name: pull test
        uses: rav2040/download-artifact-action@v1
        with:
          path: |
            .docker/foo/**/*
            .docker/bar/**/*
