name: test

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - run: |
          mkdir -p foo/bar/baz/boom
          ls foo
          ls foo/bar
          ls foo/bar/baz
          
      - uses: actions/upload-artifact@v3
        with:
          name: my-artifact
          path: foo

      - run: |
          rm -rf foo
          rm -rf .docker
          ls -al
            
      - uses: actions/download-artifact@v3
        with:
          name: my-artifact

      - run: |
          ls foo
          ls foo/bar
          ls foo/bar/baz
