name: test
on:
  workflow_dispatch:
    inputs:
      run_id:
        type: string
      environment:
        type: environment

jobs:
  build:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: echo environment
        run: echo ${{ vars.ENVIRONMENT_NAME }}
        
      - name: echo run_id
        run: echo ${{ inputs.run_id }}
