name: test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - run: |
          mkdir -p foo/bar/baz/boom
          ls foo
          ls foo/bar
          ls foo/bar/baz
          
      - uses: rav2040/upload-artifact-action@main
        with:
          path: foo
            
      - run: |
          rm -rf foo
          rm -rf .docker
          ls -al
            
      - uses: rav2040/download-artifact-action@main
        with:
          path: foo
            
      - run: |
          ls -al
