name: test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  build:
    runs-on: windows-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: TEST
        run: echo ${{ vars.ENVIRONMENT_NAME }}
