name: test

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    permissions: write
    steps:
      - uses: rav2040/git-tag-action@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: test
          message: Test message
