name: test
on:
  workflow_dispatch:
    inputs:
      environment:
        type: environment

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3

      - name: ECHO TEST
        run: echo '{"hello":"world"}'
