name: test
on:
  workflow_dispatch:
    inputs:
      run_id:
        type: string
      environment:
        type: environment

jobs:
  build:
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v3

      - name: echo environment
        run: echo ${{ vars.ENVIRONMENT_NAME }}
        
      - name: echo run_id
        run: echo ${{ inputs.run_id }}
        
      - name: Docker pull alpine
        run: docker pull alpine
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ vars.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-2
        
      - name: ECR action test
        uses: rav2040/ecr-cache-action@v1
        with:
          repository-url: 882582158506.dkr.ecr.ap-southeast-2.amazonaws.com/ubiquity-ci-image-cache
          image-tags: |
            alpine
            
