name: windows

on: push

jobs:
  run:
    runs-on: windows-latest
    steps:
      - name: Find vstest
        id: vstest
        shell: bash
        run: |
          vspath=$(vswhere \
            -latest \
            -products * \
            -requires Microsoft.VisualStudio.Workload.ManagedDesktop Microsoft.VisualStudio.Workload.Web \
            -requiresAny \
            -property installationPath)
          echo "path=$vspath\Common7\IDE\CommonExtensions\Microsoft\TestWindow\vstest.console.exe" >> $GITHUB_OUTPUT
        
      - run: |
          &("${{ steps.vstest.outputs.path }}") /TestAdapterPath:packages\NUnitTestAdapter.2.3.0 /Parallel /Logger:TRX
