name: windows

on: push

jobs:
  run:
    runs-on: windows-latest
    steps:
      - id: a
        run: |
          echo "foo=1" >> $GITHUB_OUTPUT
          
      - id: b
        run: |
          echo ${{ steps.a.outputs.foo }}       
